UserManagementUI/Controllers/UserHomeController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using UserManagementUI.Helpers;
using UserManagementUI.Models;
using static UserManagementUI.CustomAttribute.ActionParameterAttribute;

namespace UserManagementUI.Controllers
{
    [Authorize]
    public class UserHomeController : Controller
    {
        private IApiRestClient _apiRestClient;

        public UserHomeController(IApiRestClient apiRestClient)
        {
            _apiRestClient = apiRestClient;
        }

        // GET: UserHome
        [NewUserId(id = "1")]
        public ActionResult Details(Int32 id)
        {
            ViewData["UserName"] = System.Web.HttpContext.Current.User.Identity.Name;
            Task<IEnumerable<UserModel>> user = _apiRestClient.GetUserPosts(id);
            user.Wait();
            return View(user.Result.Take(5));
        }

        // GET: UserHome
        [NewUserId(id = "1")]
        public ActionResult Index(Int32 id)
        {
           Task<object> user = _apiRestClient.GetUserContent(id);
            user.Wait();
            ViewBag.User = user.Result;
            var username = ViewBag.User.username;
            return View();
        }

        public ActionResult CreateUser(UserModel userModel)
        {
            if (string.IsNullOrEmpty(userModel.title))
                ModelState.AddModelError("Title", "Title is Required.");
            if (string.IsNullOrEmpty(userModel.body))
                ModelState.AddModelError("Body", "Body is Required.");
            if (ModelState.IsValid)
            {
                Task<UserModel> glossary = _apiRestClient.PostUser(userModel);
                glossary.Wait();

            }
            else
                return View(userModel);
            return RedirectToAction("Index");
        }
    }
}

UserManagementUI/Views/UserHome/Details.cshtml
@model IEnumerable<UserManagementUI.Models.UserModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-login">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div style="overflow-x:auto;">
                                <table class="mytable">
                                    <tr>
                                        <th>Title</th>
                                        <th>Body</th>
                                    </tr>
                                    @foreach (var row in Model)
                                    {
                                        <tr id="tr@(row)">
                                            <td>@row.title</td>
                                            <td>@row.body</td>
                                        </tr>
                                    }
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

UserManagementUI/Views/UserHome/Index.cshtml
@{
    ViewBag.Title = "Details";
}
<h3>Welcome @ViewBag.User.username<h3>
<div class="row">
    <div class="col-md-6">
        <label>Name:</label>
		<span>@ViewBag.User.name</span></div>
	<div class="col-md-6">
		<label>Email:</label>
		<span>@ViewBag.User.email/span>
    </div>
	<br/>
	<br/>
	<div class="col-md-6">
        <label>Phone:</label>
		<span>@ViewBag.User.phone</span>
	</div>
	<div class="col-md-6">
		<label>Website:</label>
		<span>@ViewBag.User.website</span>
    </div>
	<br/>
	<br/>
	<div class="col-md-12">
		@Html.ActionLink("Details", "Details", "UserHome")
    </div>
</div> 